import React, { useMemo } from 'react';
import { AlertTriangle, BarChart3, Calendar, CheckCircle2, Coins, Megaphone, Share2 } from 'lucide-react';
import type { Campaign, Company, ScheduledPost, Wallet } from '../types';
interface Props { selectedCompany:Company|null; wallet:Wallet|null; campaigns:Campaign[]; scheduledPosts:ScheduledPost[]; onNavigate:(tab:string)=>void; }
export const AnalyticsPage:React.FC<Props>=({selectedCompany,wallet,campaigns,scheduledPosts,onNavigate})=>{
 const posts=useMemo(()=>scheduledPosts.filter(p=>!selectedCompany||p.companyId===selectedCompany.id),[scheduledPosts,selectedCompany]);
 const camps=useMemo(()=>campaigns.filter(c=>!selectedCompany||c.companyId===selectedCompany.id),[campaigns,selectedCompany]);
 const published=posts.filter(p=>p.status==='published').length, failed=posts.filter(p=>p.status==='failed').length, queued=posts.filter(p=>p.status==='scheduled'||p.status==='publishing').length;
 const completed=published+failed; const successRateText=completed?`${Math.round((published/completed)*100)}%`:'Sem dados';
 const platformCounts=useMemo(()=>{const map=new Map<string,number>();for(const p of posts)for(const platform of p.platforms||[])map.set(platform,(map.get(platform)||0)+1);return [...map.entries()].sort((a,b)=>b[1]-a[1])},[posts]);
 const max=Math.max(1,...platformCounts.map(([,v])=>v));
 const campaignTotals=camps.reduce((acc,c)=>({reach:acc.reach+Number(c.metrics?.reach||0),clicks:acc.clicks+Number(c.metrics?.clicks||0),leads:acc.leads+Number(c.metrics?.leads||0),conversions:acc.conversions+Number(c.metrics?.conversions||0)}),{reach:0,clicks:0,leads:0,conversions:0});
 return <div className="mx-auto max-w-6xl space-y-6 animate-fadeIn"><header><h2 className="flex items-center gap-2 text-xl font-black text-white"><BarChart3 className="text-cyan-400"/>Analytics operacional</h2><p className="text-xs text-slate-400">Somente métricas registradas pelo sistema; sem percentuais estimados ou dados decorativos.</p></header>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[[CheckCircle2,'Publicados',published,'text-emerald-300'],[Calendar,'Na fila',queued,'text-cyan-300'],[AlertTriangle,'Falhas',failed,'text-rose-300'],[Megaphone,'Campanhas ativas',camps.filter(c=>c.status==='active').length,'text-amber-300'],[Coins,'Saldo de créditos',wallet?.balance??0,'text-white']].map(([Icon,label,value,color]:any)=><div key={label} className="froc-panel"><Icon size={17} className="text-cyan-400"/><div className="mt-3 text-[10px] font-black uppercase tracking-wider text-slate-500">{label}</div><div className={`mt-1 text-3xl font-black ${color}`}>{Number(value).toLocaleString('pt-BR')}</div></div>)}</div>
 <div className="grid gap-6 lg:grid-cols-2"><section className="froc-panel"><div className="mb-4 flex items-center justify-between"><h3 className="froc-section-title">Publicações por canal</h3><span className="text-[10px] text-slate-500">{posts.length} agendamentos</span></div>{platformCounts.length?<div className="space-y-4">{platformCounts.map(([name,count])=><div key={name}><div className="mb-1 flex justify-between text-xs"><span className="font-semibold text-slate-200">{name}</span><span className="text-cyan-300">{count}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-gradient-to-r from-blue-600 to-cyan-400" style={{width:`${Math.max(4,(count/max)*100)}%`}}/></div></div>)}</div>:<div className="py-10 text-center text-xs text-slate-500">Ainda não há publicações registradas para esta empresa.</div>}</section>
 <section className="froc-panel"><h3 className="froc-section-title mb-4">Confiabilidade da publicação</h3><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-slate-800 bg-slate-950/50 p-5"><div className="text-[10px] font-bold uppercase text-slate-500">Taxa de sucesso</div><div className={`mt-1 font-black ${completed ? 'text-4xl text-emerald-300' : 'text-2xl text-slate-400'}`}>{successRateText}</div><div className="mt-1 text-[10px] text-slate-500">{completed ? 'Calculada apenas sobre tentativas concluídas.' : 'Nenhuma publicação finalizada ainda.'}</div></div><div className="rounded-2xl border border-slate-800 bg-slate-950/50 p-5"><div className="text-[10px] font-bold uppercase text-slate-500">Créditos usados</div><div className="mt-1 text-4xl font-black text-amber-300">{wallet?.totalUsed??0}</div><div className="mt-1 text-[10px] text-slate-500">Ledger da conta.</div></div></div>{failed>0&&<button onClick={()=>onNavigate('calendario')} className="mt-4 w-full rounded-xl border border-rose-500/25 bg-rose-500/10 px-4 py-3 text-xs font-bold text-rose-300">Revisar {failed} publicação(ões) com falha</button>}</section></div>
 <section className="froc-panel"><div className="mb-4 flex items-center justify-between"><h3 className="froc-section-title">Métricas registradas nas campanhas</h3><span className="text-[10px] text-slate-500">Sem inferência externa</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Alcance',campaignTotals.reach],['Cliques',campaignTotals.clicks],['Leads',campaignTotals.leads],['Conversões',campaignTotals.conversions]].map(([label,value])=><div key={label as string} className="rounded-2xl border border-slate-800 bg-slate-950/50 p-4"><div className="text-[10px] font-bold uppercase text-slate-500">{label}</div><div className="mt-1 text-2xl font-black text-white">{Number(value).toLocaleString('pt-BR')}</div></div>)}</div><p className="mt-4 flex items-start gap-2 text-[10px] leading-5 text-slate-500"><Share2 size={13} className="mt-1 shrink-0"/>Redes que não disponibilizam coleta automática de métricas pela permissão atual permanecem em zero; o painel não inventa resultados.</p></section></div>;
};
