import React, { useState } from 'react';
import { Calendar, Megaphone, Pause, Play, Plus, Trash2 } from 'lucide-react';
import type { Campaign, Company } from '../types';
import { apiRequest } from '../lib/api';
interface CampaignsPageProps{campaigns:Campaign[];selectedCompany:Company|null;onRefreshCampaigns:()=>void|Promise<void>;onNavigate:(tab:string)=>void;}
export const CampaignsPage:React.FC<CampaignsPageProps>=({campaigns,selectedCompany,onRefreshCampaigns,onNavigate})=>{
 const [open,setOpen]=useState(false),[name,setName]=useState(''),[objective,setObjective]=useState('Conversão e Vendas'),[platforms,setPlatforms]=useState<string[]>(['Instagram','Facebook']),[startDate,setStartDate]=useState(new Date().toISOString().slice(0,10)),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const visible=selectedCompany?campaigns.filter(c=>c.companyId===selectedCompany.id):campaigns;
 const toggle=(p:string)=>setPlatforms(v=>v.includes(p)?v.filter(x=>x!==p):[...v,p]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();if(!selectedCompany){setError('Selecione uma empresa antes de criar uma campanha.');return;}setLoading(true);setError('');try{await apiRequest('/api/campaigns',{method:'POST',body:{companyId:selectedCompany.id,name,objective,targetPlatforms:platforms,startDate,status:'active'}});setOpen(false);setName('');await onRefreshCampaigns()}catch(err:any){setError(err.message||'Falha ao criar campanha.')}finally{setLoading(false)}};
 const patch=async(c:Campaign,status:Campaign['status'])=>{setError('');try{await apiRequest(`/api/campaigns/${c.id}`,{method:'PATCH',body:{status}});await onRefreshCampaigns()}catch(e:any){setError(e.message||'Falha ao atualizar campanha.')}};
 const remove=async(c:Campaign)=>{if(!window.confirm(`Excluir a campanha “${c.name}”?`))return;try{await apiRequest(`/api/campaigns/${c.id}`,{method:'DELETE'});await onRefreshCampaigns()}catch(e:any){setError(e.message||'Falha ao excluir campanha.')}};
 return <div className="mx-auto max-w-6xl space-y-6 animate-fadeIn"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="flex items-center gap-2 text-xl font-bold text-white"><Megaphone className="text-cyan-400"/>Campanhas</h2><p className="mt-1 text-xs text-slate-400">Planeje objetivos e canais sem inventar métricas: alcance, cliques e conversões só aparecem quando existem dados reais.</p></div><button onClick={()=>selectedCompany?setOpen(true):onNavigate('empresa')} className="min-h-11 rounded-xl bg-gradient-to-r from-blue-600 to-cyan-500 px-5 text-xs font-extrabold text-white"><Plus size={15} className="mr-1 inline"/>Nova campanha</button></div>{error&&<div className="rounded-2xl border border-rose-500/30 bg-rose-500/10 p-4 text-xs text-rose-200">{error}</div>}
 {visible.length?<div className="grid grid-cols-1 gap-4 md:grid-cols-2">{visible.map(c=><article key={c.id} className="rounded-3xl border border-[#334155] bg-[#0F172A] p-5"><div className="flex items-start justify-between gap-3"><div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${c.status==='active'?'bg-emerald-500/10 text-emerald-300':c.status==='paused'?'bg-amber-500/10 text-amber-300':'bg-slate-800 text-slate-400'}`}>{c.status.toUpperCase()}</span><h3 className="mt-3 text-base font-bold text-white">{c.name}</h3><p className="mt-1 text-xs text-slate-400">{c.objective}</p></div><span className="flex items-center gap-1 text-[10px] text-slate-500"><Calendar size={12}/>{new Date(c.startDate).toLocaleDateString('pt-BR')}</span></div><div className="mt-4 flex flex-wrap gap-1">{c.targetPlatforms.map(p=><span key={p} className="rounded-lg border border-slate-700 bg-slate-800 px-2 py-1 text-[10px] text-slate-300">{p}</span>)}</div><div className="mt-5 grid grid-cols-4 gap-2 border-t border-slate-800 pt-4">{[['Alcance',c.metrics?.reach],['Cliques',c.metrics?.clicks],['Leads',c.metrics?.leads],['Conversões',c.metrics?.conversions]].map(([label,value])=><div key={String(label)} className="rounded-xl bg-slate-900/70 p-2 text-center"><span className="block text-[9px] text-slate-500">{label}</span><strong className="text-xs text-white">{value !== undefined && value !== null ? Number(value) : '—'}</strong></div>)}</div><div className="mt-4 flex gap-2">{c.status==='active'?<button onClick={()=>void patch(c,'paused')} className="flex min-h-10 flex-1 items-center justify-center gap-1 rounded-xl border border-amber-500/30 bg-amber-500/10 text-[11px] font-bold text-amber-300"><Pause size={13}/>Pausar</button>:<button onClick={()=>void patch(c,'active')} className="flex min-h-10 flex-1 items-center justify-center gap-1 rounded-xl border border-emerald-500/30 bg-emerald-500/10 text-[11px] font-bold text-emerald-300"><Play size={13}/>Ativar</button>}<button onClick={()=>void remove(c)} className="flex min-h-10 items-center justify-center gap-1 rounded-xl border border-rose-500/30 bg-rose-500/10 px-4 text-[11px] font-bold text-rose-300"><Trash2 size={13}/>Excluir</button></div></article>)}</div>:<div className="rounded-3xl border border-[#334155] bg-[#0F172A] p-12 text-center"><Megaphone size={42} className="mx-auto text-slate-700"/><h3 className="mt-3 text-sm font-bold text-slate-300">Nenhuma campanha ainda</h3><p className="mt-1 text-xs text-slate-500">Crie uma campanha para organizar objetivos, canais e conteúdos.</p></div>}
 {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/80 p-4 backdrop-blur-sm"><form onSubmit={create} className="w-full max-w-lg space-y-4 rounded-3xl border border-[#334155] bg-[#0F172A] p-6"><h3 className="text-base font-bold text-white">Nova campanha · {selectedCompany?.name}</h3><label className="block text-xs text-slate-300">Nome<input required value={name} onChange={e=>setName(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-slate-700 bg-[#1E293B] px-3 text-white outline-none focus:border-cyan-400"/></label><label className="block text-xs text-slate-300">Objetivo<select value={objective} onChange={e=>setObjective(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-slate-700 bg-[#1E293B] px-3 text-white"><option>Conversão e Vendas</option><option>Atração de Leads</option><option>Reconhecimento de Marca</option><option>Engajamento e Comunidade</option></select></label><label className="block text-xs text-slate-300">Início<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-slate-700 bg-[#1E293B] px-3 text-white"/></label><div><span className="text-xs text-slate-300">Canais</span><div className="mt-2 flex flex-wrap gap-2">{['Instagram','Facebook','LinkedIn','TikTok','YouTube','Pinterest','X'].map(p=><button type="button" key={p} onClick={()=>toggle(p)} className={`min-h-10 rounded-xl border px-3 text-xs ${platforms.includes(p)?'border-cyan-400 bg-cyan-500/10 text-cyan-300':'border-slate-700 bg-slate-800 text-slate-400'}`}>{p}</button>)}</div></div><div className="flex justify-end gap-2 pt-2"><button type="button" onClick={()=>setOpen(false)} className="min-h-11 rounded-xl bg-slate-800 px-4 text-xs font-bold text-slate-300">Cancelar</button><button disabled={loading} className="min-h-11 rounded-xl bg-gradient-to-r from-blue-600 to-cyan-500 px-5 text-xs font-extrabold text-white disabled:opacity-50">{loading?'Salvando…':'Criar campanha'}</button></div></form></div>}
 </div>;
};
