import React, { useEffect, useState } from 'react';
import { ArrowDownLeft, ArrowUpRight, Coins, CreditCard, RefreshCw } from 'lucide-react';
import type { CreditTransaction, Wallet } from '../types';
import { apiRequest } from '../lib/api';

interface Props { wallet:Wallet|null; onRefreshWallet:()=>void; onNavigate:(tab:string)=>void; }
export const CreditsPage:React.FC<Props>=({wallet,onRefreshWallet,onNavigate})=>{
 const[transactions,setTransactions]=useState<CreditTransaction[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const d=await apiRequest<{transactions:CreditTransaction[]}>('/api/credits/history');setTransactions(d.transactions||[])}catch(err:any){setError(err.message||'Falha ao carregar extrato.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const positive=(tx:CreditTransaction)=>Number(tx.amount)>0;
 return <div className="mx-auto max-w-5xl space-y-6 animate-fadeIn"><header className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="flex items-center gap-2 text-xl font-black text-white"><Coins className="text-amber-400"/>Extrato e Gestão de Créditos</h2><p className="text-xs text-slate-400">Ledger transacional com compras, assinaturas, bônus, uso, ajustes e reversões.</p></div><button onClick={()=>onNavigate('planos')} className="froc-primary inline-flex items-center justify-center gap-2"><CreditCard size={15}/>Planos e créditos</button></header>
 {error&&<div className="rounded-2xl border border-rose-500/20 bg-rose-500/10 p-3 text-xs text-rose-300">{error}</div>}
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Saldo atual',wallet?.balance??0,'text-amber-300'],['Bônus',wallet?.bonusBalance??0,'text-cyan-300'],['Total consumido',wallet?.totalUsed??0,'text-rose-300'],['Total recebido',wallet?.totalReceived??0,'text-emerald-300']].map(([label,value,color]:any)=><div key={label} className="froc-panel"><div className="text-[10px] font-black uppercase tracking-wider text-slate-500">{label}</div><div className={`mt-2 text-3xl font-black ${color}`}>{Number(value).toLocaleString('pt-BR')}</div><div className="mt-1 text-[10px] text-slate-500">créditos</div></div>)}</div>
 <section className="froc-panel"><div className="mb-4 flex items-center justify-between border-b border-slate-800 pb-3"><h3 className="froc-section-title">Histórico de transações</h3><button onClick={()=>{void load();onRefreshWallet()}} className="rounded-xl border border-slate-700 p-2 text-slate-400 hover:text-white" aria-label="Atualizar extrato"><RefreshCw size={14} className={loading?'animate-spin':''}/></button></div>{transactions.length?<div className="divide-y divide-slate-800/70">{transactions.map(tx=>{const credit=positive(tx);return <div key={tx.id} className="flex items-center justify-between gap-4 py-3"><div className="flex min-w-0 items-center gap-3"><div className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl ${credit?'bg-emerald-500/10 text-emerald-300':'bg-rose-500/10 text-rose-300'}`}>{credit?<ArrowDownLeft size={16}/>:<ArrowUpRight size={16}/>}</div><div className="min-w-0"><div className="truncate text-xs font-bold text-white">{tx.source||tx.type}</div><div className="mt-0.5 text-[10px] text-slate-500">{new Date(tx.timestamp).toLocaleString('pt-BR')} · {tx.type.replaceAll('_',' ')}</div></div></div><div className="shrink-0 text-right"><div className={`text-sm font-black ${credit?'text-emerald-300':'text-rose-300'}`}>{credit?'+':''}{tx.amount}</div><div className="text-[10px] text-slate-500">Saldo: {tx.balanceAfter}</div></div></div>})}</div>:<div className="py-10 text-center text-xs text-slate-500">Nenhuma transação registrada.</div>}</section></div>;
};
