import React, { useEffect, useState } from 'react';
import { ChevronDown, ChevronUp, HelpCircle, Mail, MessageSquare, Send } from 'lucide-react';
import { apiRequest } from '../lib/api';

interface Props { onNavigate: (tab: string) => void; }
export const SupportPage: React.FC<Props> = () => {
  const [openFaq, setOpenFaq] = useState<number|null>(0);
  const [subject, setSubject] = useState('');
  const [message, setMessage] = useState('');
  const [sending, setSending] = useState(false);
  const [feedback, setFeedback] = useState('');
  const [contact, setContact] = useState<{email:string;whatsapp?:string|null}>({email:'brasilportalvip@gmail.com'});
  useEffect(()=>{ apiRequest<{email:string;whatsapp?:string|null}>('/api/support/contact').then(setContact).catch(()=>undefined); },[]);
  const faqs = [
    ['Como funcionam os créditos?', 'Cada operação de IA consome o custo exibido pela plataforma. A carteira e o extrato são gravados no backend com idempotência para evitar cobranças duplicadas.'],
    ['O Autopilot publica sozinho?', 'No modo automático ele tenta publicar apenas em redes conectadas e compatíveis com o tipo de conteúdo. Uma falha externa nunca é marcada como sucesso.'],
    ['Quantas empresas posso cadastrar?', 'START: 2, PRO: 5, BUSINESS: 15 e AGENCY: ilimitadas.'],
    ['Como o pagamento é confirmado?', 'O Mercado Pago confirma o pagamento via webhook assinado; o backend valida a assinatura, o valor e a referência antes de liberar créditos.'],
    ['Como a IA usa minha marca?', 'O perfil da empresa, público, tom de voz, produtos, serviços, diferenciais e palavras-chave entram no contexto de geração.']
  ];
  const submit = async (e:React.FormEvent)=>{e.preventDefault();setSending(true);setFeedback('');try{await apiRequest('/api/support/tickets',{method:'POST',body:{subject,message}});setSubject('');setMessage('');setFeedback('Chamado aberto com sucesso. Ele ficou registrado na plataforma.');}catch(err:any){setFeedback(err.message||'Falha ao abrir chamado.');}finally{setSending(false)}};
  return <div className="mx-auto max-w-5xl space-y-7 animate-fadeIn"><div><h2 className="flex items-center gap-2 text-xl font-bold text-white"><HelpCircle className="text-cyan-400"/>Central de Ajuda & Suporte</h2><p className="text-xs text-slate-400">Suporte com chamado persistido — sem mensagem de sucesso simulada.</p></div><div className="grid gap-4 md:grid-cols-2"><a href={`mailto:${contact.email}`} className="froc-panel flex items-center gap-4 hover:border-cyan-500/50"><Mail className="text-cyan-400"/><div><div className="text-sm font-bold text-white">E-mail de suporte</div><div className="text-xs text-slate-400">{contact.email}</div></div></a>{contact.whatsapp?<a href={`https://wa.me/${contact.whatsapp.replace(/\D/g,'')}`} target="_blank" rel="noreferrer" className="froc-panel flex items-center gap-4 hover:border-emerald-500/50"><MessageSquare className="text-emerald-400"/><div><div className="text-sm font-bold text-white">WhatsApp oficial</div><div className="text-xs text-slate-400">Abrir atendimento</div></div></a>:<div className="froc-panel flex items-center gap-4 opacity-70"><MessageSquare className="text-slate-500"/><div><div className="text-sm font-bold text-white">WhatsApp</div><div className="text-xs text-slate-500">Canal ainda não configurado.</div></div></div>}</div><section className="froc-panel"><h3 className="froc-section-title mb-4">Perguntas frequentes</h3><div className="space-y-2">{faqs.map(([q,a],i)=><div key={q} className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/70"><button onClick={()=>setOpenFaq(openFaq===i?null:i)} className="flex w-full items-center justify-between p-4 text-left text-xs font-bold text-white"><span>{q}</span>{openFaq===i?<ChevronUp size={15}/>:<ChevronDown size={15}/>}</button>{openFaq===i&&<div className="border-t border-slate-800 px-4 py-3 text-xs leading-relaxed text-slate-300">{a}</div>}</div>)}</div></section><section className="froc-panel"><h3 className="froc-section-title mb-4">Abrir chamado</h3>{feedback&&<div className="mb-4 rounded-xl border border-cyan-500/20 bg-cyan-500/10 p-3 text-xs text-cyan-200">{feedback}</div>}<form onSubmit={submit} className="space-y-4"><label className="text-xs font-semibold text-slate-300">Assunto<input value={subject} onChange={(e)=>setSubject(e.target.value)} className="froc-input mt-1.5" required maxLength={300}/></label><label className="text-xs font-semibold text-slate-300">Descrição<textarea value={message} onChange={(e)=>setMessage(e.target.value)} className="froc-input mt-1.5 min-h-32 resize-y" required maxLength={10000}/></label><button disabled={sending} className="froc-primary flex items-center gap-2"><Send size={15}/>{sending?'Enviando…':'Abrir chamado'}</button></form></section></div>;
};
